import VeiledFlock.ProductionCombinedMerkleTransport

/-!
# Finite production oracle transport

The byte-level Merkle model uses the convenient total function
`List Byte → OracleBlock`.  A uniformly sampled random oracle, however, must
have a finite domain in the finite probability model used by this
development.  This file embeds every production query into `BoundedBytes`,
performs the joint algebraic-coin/hidden-leaf permutation there, and proves
that the two roots and the complete bounded equality sampler are preserved.
-/

namespace VeiledFlock.ProductionBoundedOracle

open Function
open VeiledFlock.CoinOracleTransport
open VeiledFlock.ConcreteOracle
open VeiledFlock.Framing
open VeiledFlock.NonceSerialization
open VeiledFlock.ProductionCombinedMerkleTransport
open VeiledFlock.ProductionEqualitySampler
open VeiledFlock.ProductionFraming
open VeiledFlock.ProductionMerklePrelude
open VeiledFlock.ProductionMerkleTree
open VeiledFlock.ProductionTranscriptFraming

/-- Interpret a finite bounded oracle as a byte-list oracle.  Queries outside
the audited production budget fail closed to an explicit public fallback;
all theorems below prove that the relevant queries take the bounded branch. -/
noncomputable def answerBounded {maxLength : ℕ} (fallback : OracleBlock)
    (oracle : BoundedBytes maxLength → OracleBlock)
    (point : List Byte) : OracleBlock :=
  if h : point.length ≤ maxLength then oracle (boundBytes point h)
  else fallback

@[simp]
theorem answerBounded_of_le {maxLength : ℕ} (fallback : OracleBlock)
    (oracle : BoundedBytes maxLength → OracleBlock) (point : List Byte)
    (hpoint : point.length ≤ maxLength) :
    answerBounded fallback oracle point = oracle (boundBytes point hpoint) := by
  simp only [answerBounded, dif_pos hpoint]

/-- Every leaf point generated by the material fits into the finite oracle
domain. -/
def MaterialFits {Coins : Type*} {maxLength : ℕ}
    (geometry : TreeGeometry) (material : TreeMaterial geometry Coins) : Prop :=
  ∀ coins index, 108 + (material.payload coins index).length ≤ maxLength

theorem leafPoint_length {Coins : Type*} (geometry : TreeGeometry)
    (material : TreeMaterial geometry Coins) (coins : Coins)
    (index : Fin (2 ^ geometry.depth)) :
    (leafPoint geometry material coins index).length =
      108 + (material.payload coins index).length := by
  simp [leafPoint]

theorem leafPoint_fits {Coins : Type*} {maxLength : ℕ}
    (geometry : TreeGeometry) (material : TreeMaterial geometry Coins)
    (hfits : MaterialFits (maxLength := maxLength) geometry material)
    (coins : Coins) (index : Fin (2 ^ geometry.depth)) :
    (leafPoint geometry material coins index).length ≤ maxLength := by
  rw [leafPoint_length]
  exact hfits coins index

/-- The exact combined outer/linear leaf family, now represented inside the
finite bounded oracle domain. -/
noncomputable def boundedCombinedLeafPoint {Coins : Type*} {maxLength : ℕ}
    (outer linear : TreeGeometry)
    (outerMaterial : TreeMaterial outer Coins)
    (linearMaterial : TreeMaterial linear Coins)
    (houter : MaterialFits (maxLength := maxLength) outer outerMaterial)
    (hlinear : MaterialFits (maxLength := maxLength) linear linearMaterial)
    (coins : Coins) (index : CombinedIndex outer linear) :
    BoundedBytes maxLength :=
  match index with
  | .inl outerIndex =>
      boundBytes (leafPoint outer outerMaterial coins outerIndex)
        (leafPoint_fits outer outerMaterial houter coins outerIndex)
  | .inr linearIndex =>
      boundBytes (leafPoint linear linearMaterial coins linearIndex)
        (leafPoint_fits linear linearMaterial hlinear coins linearIndex)

@[simp]
theorem unbound_boundedCombinedLeafPoint {Coins : Type*} {maxLength : ℕ}
    (outer linear : TreeGeometry)
    (outerMaterial : TreeMaterial outer Coins)
    (linearMaterial : TreeMaterial linear Coins)
    (houter : MaterialFits (maxLength := maxLength) outer outerMaterial)
    (hlinear : MaterialFits (maxLength := maxLength) linear linearMaterial)
    (coins : Coins) (index : CombinedIndex outer linear) :
    unboundBytes
        (boundedCombinedLeafPoint outer linear outerMaterial linearMaterial
          houter hlinear coins index) =
      combinedLeafPoint outer linear outerMaterial linearMaterial coins index := by
  cases index <;> rfl

theorem boundedCombinedLeafPoint_injective {Coins : Type*} {maxLength : ℕ}
    (outer linear : TreeGeometry) (hchannels : outer.channel ≠ linear.channel)
    (outerMaterial : TreeMaterial outer Coins)
    (linearMaterial : TreeMaterial linear Coins)
    (houter : MaterialFits (maxLength := maxLength) outer outerMaterial)
    (hlinear : MaterialFits (maxLength := maxLength) linear linearMaterial)
    (coins : Coins) :
    Injective (boundedCombinedLeafPoint outer linear outerMaterial
      linearMaterial houter hlinear coins) := by
  intro left right heq
  apply combinedLeafPoint_injective outer linear hchannels outerMaterial
    linearMaterial coins
  simpa using congrArg unboundBytes heq

theorem boundedCombinedLeafPoint_cross {Coins : Type*} {maxLength : ℕ}
    (coinEquiv : Coins ≃ Coins)
    (outer linear : TreeGeometry) (hchannels : outer.channel ≠ linear.channel)
    (leftOuter : TreeMaterial outer Coins)
    (leftLinear : TreeMaterial linear Coins)
    (rightOuter : TreeMaterial outer Coins)
    (rightLinear : TreeMaterial linear Coins)
    (hleftOuter : MaterialFits (maxLength := maxLength) outer leftOuter)
    (hleftLinear : MaterialFits (maxLength := maxLength) linear leftLinear)
    (hrightOuter : MaterialFits (maxLength := maxLength) outer rightOuter)
    (hrightLinear : MaterialFits (maxLength := maxLength) linear rightLinear)
    (coins : Coins) (leftIndex rightIndex : CombinedIndex outer linear)
    (heq :
      boundedCombinedLeafPoint outer linear leftOuter leftLinear hleftOuter
          hleftLinear coins leftIndex =
        boundedCombinedLeafPoint outer linear rightOuter rightLinear
          hrightOuter hrightLinear (coinEquiv coins) rightIndex) :
    leftIndex = rightIndex := by
  apply combinedLeafPoint_cross coinEquiv outer linear hchannels leftOuter
    leftLinear rightOuter rightLinear coins leftIndex rightIndex
  simpa using congrArg unboundBytes heq

/-- Joint algebraic-coin/oracle bijection over the genuinely finite oracle
domain. -/
noncomputable def boundedCombinedCoinOracleEquiv {Coins : Type*}
    {maxLength : ℕ} (coinEquiv : Coins ≃ Coins)
    (outer linear : TreeGeometry) (hchannels : outer.channel ≠ linear.channel)
    (leftOuter : TreeMaterial outer Coins)
    (leftLinear : TreeMaterial linear Coins)
    (rightOuter : TreeMaterial outer Coins)
    (rightLinear : TreeMaterial linear Coins)
    (hleftOuter : MaterialFits (maxLength := maxLength) outer leftOuter)
    (hleftLinear : MaterialFits (maxLength := maxLength) linear leftLinear)
    (hrightOuter : MaterialFits (maxLength := maxLength) outer rightOuter)
    (hrightLinear : MaterialFits (maxLength := maxLength) linear rightLinear) :
    (Coins × (BoundedBytes maxLength → OracleBlock)) ≃
      (Coins × (BoundedBytes maxLength → OracleBlock)) :=
  CoinOracleTransport.coinOracleEquiv coinEquiv
    (boundedCombinedLeafPoint outer linear leftOuter leftLinear hleftOuter
      hleftLinear)
    (boundedCombinedLeafPoint outer linear rightOuter rightLinear hrightOuter
      hrightLinear)
    (fun coins => boundedCombinedLeafPoint_injective outer linear hchannels
      leftOuter leftLinear hleftOuter hleftLinear coins)
    (fun coins => boundedCombinedLeafPoint_injective outer linear hchannels
      rightOuter rightLinear hrightOuter hrightLinear coins)
    (fun coins => boundedCombinedLeafPoint_cross coinEquiv outer linear
      hchannels leftOuter leftLinear rightOuter rightLinear hleftOuter
      hleftLinear hrightOuter hrightLinear coins)

/-- Evaluating a bounded point outside both moved leaf families is exactly
unchanged by the finite joint transport. -/
theorem boundedCombinedCoinOracleEquiv_answer_off {Coins : Type*}
    {maxLength : ℕ} (coinEquiv : Coins ≃ Coins)
    (outer linear : TreeGeometry) (hchannels : outer.channel ≠ linear.channel)
    (leftOuter : TreeMaterial outer Coins)
    (leftLinear : TreeMaterial linear Coins)
    (rightOuter : TreeMaterial outer Coins)
    (rightLinear : TreeMaterial linear Coins)
    (hleftOuter : MaterialFits (maxLength := maxLength) outer leftOuter)
    (hleftLinear : MaterialFits (maxLength := maxLength) linear leftLinear)
    (hrightOuter : MaterialFits (maxLength := maxLength) outer rightOuter)
    (hrightLinear : MaterialFits (maxLength := maxLength) linear rightLinear)
    (fallback : OracleBlock)
    (input : Coins × (BoundedBytes maxLength → OracleBlock))
    (point : List Byte) (hpoint : point.length ≤ maxLength)
    (hoffLeft : ∀ index,
      point ≠ combinedLeafPoint outer linear leftOuter leftLinear input.1 index)
    (hoffRight : ∀ index,
      point ≠ combinedLeafPoint outer linear rightOuter rightLinear
        (coinEquiv input.1) index) :
    let transported := boundedCombinedCoinOracleEquiv coinEquiv outer linear
      hchannels leftOuter leftLinear rightOuter rightLinear hleftOuter
      hleftLinear hrightOuter hrightLinear input
    answerBounded fallback transported.2 point =
      answerBounded fallback input.2 point := by
  classical
  dsimp only
  rw [answerBounded_of_le fallback _ point hpoint,
    answerBounded_of_le fallback _ point hpoint]
  apply CoinOracleTransport.coinOracleEquiv_off
  · intro index heq
    apply hoffLeft index
    simpa using congrArg unboundBytes heq
  · intro index heq
    apply hoffRight index
    simpa using congrArg unboundBytes heq

/-- Evaluate a production tree against the finite oracle adapter. -/
noncomputable def boundedRoot {Coins : Type*} {maxLength : ℕ}
    (fallback : OracleBlock) (geometry : TreeGeometry)
    (material : TreeMaterial geometry Coins) (coins : Coins)
    (oracle : BoundedBytes maxLength → OracleBlock) : OracleBlock :=
  root geometry material coins (answerBounded fallback oracle)

/-- The finite joint transport makes both initial production roots exactly
equal.  The only non-leaf queries are the 140-byte internal-node frames. -/
theorem boundedCombinedCoinOracleEquiv_roots_exact {Coins : Type*}
    {maxLength : ℕ} (coinEquiv : Coins ≃ Coins)
    (outer linear : TreeGeometry) (hchannels : outer.channel ≠ linear.channel)
    (leftOuter : TreeMaterial outer Coins)
    (leftLinear : TreeMaterial linear Coins)
    (rightOuter : TreeMaterial outer Coins)
    (rightLinear : TreeMaterial linear Coins)
    (hleftOuter : MaterialFits (maxLength := maxLength) outer leftOuter)
    (hleftLinear : MaterialFits (maxLength := maxLength) linear leftLinear)
    (hrightOuter : MaterialFits (maxLength := maxLength) outer rightOuter)
    (hrightLinear : MaterialFits (maxLength := maxLength) linear rightLinear)
    (hnodes : 140 ≤ maxLength) (fallback : OracleBlock)
    (input : Coins × (BoundedBytes maxLength → OracleBlock)) :
    let transported := boundedCombinedCoinOracleEquiv coinEquiv outer linear
      hchannels leftOuter leftLinear rightOuter rightLinear hleftOuter
      hleftLinear hrightOuter hrightLinear input
    boundedRoot fallback outer rightOuter (coinEquiv input.1) transported.2 =
        boundedRoot fallback outer leftOuter input.1 input.2 ∧
      boundedRoot fallback linear rightLinear (coinEquiv input.1)
          transported.2 =
        boundedRoot fallback linear leftLinear input.1 input.2 := by
  classical
  dsimp only
  let leftPoint := boundedCombinedLeafPoint outer linear leftOuter leftLinear
    hleftOuter hleftLinear
  let rightPoint := boundedCombinedLeafPoint outer linear rightOuter rightLinear
    hrightOuter hrightLinear
  let hleft := fun coins => boundedCombinedLeafPoint_injective outer linear
    hchannels leftOuter leftLinear hleftOuter hleftLinear coins
  let hright := fun coins => boundedCombinedLeafPoint_injective outer linear
    hchannels rightOuter rightLinear hrightOuter hrightLinear coins
  let hcross := fun coins => boundedCombinedLeafPoint_cross coinEquiv outer
    linear hchannels leftOuter leftLinear rightOuter rightLinear hleftOuter
    hleftLinear hrightOuter hrightLinear coins
  let transported := boundedCombinedCoinOracleEquiv coinEquiv outer linear
    hchannels leftOuter leftLinear rightOuter rightLinear hleftOuter hleftLinear
    hrightOuter hrightLinear input
  constructor
  · unfold boundedRoot root productionMerkleRoot
    apply merkleRoot_congr (answerBounded fallback input.2)
      (answerBounded fallback transported.2)
      (productionNodePoint outer.channel outer.treeDepth outer.treeNonce)
    · intro level index left right
      exact boundedCombinedCoinOracleEquiv_answer_off coinEquiv outer linear
        hchannels leftOuter leftLinear rightOuter rightLinear hleftOuter
        hleftLinear hrightOuter hrightLinear fallback input
        (productionNodePoint outer.channel outer.treeDepth outer.treeNonce
          level index left right) (by simpa using hnodes)
        (outerNode_ne_combinedLeaf outer linear hchannels leftOuter leftLinear
          input.1 level index left right)
        (outerNode_ne_combinedLeaf outer linear hchannels rightOuter
          rightLinear (coinEquiv input.1) level index left right)
    · intro index
      change answerBounded fallback transported.2
          (leafPoint outer rightOuter (coinEquiv input.1) index) =
        answerBounded fallback input.2
          (leafPoint outer leftOuter input.1 index)
      rw [answerBounded_of_le fallback transported.2 _
          (leafPoint_fits outer rightOuter hrightOuter (coinEquiv input.1)
            index),
        answerBounded_of_le fallback input.2 _
          (leafPoint_fits outer leftOuter hleftOuter input.1 index)]
      exact CoinOracleTransport.coinOracleEquiv_at_right coinEquiv leftPoint
        rightPoint hleft hright hcross input (Sum.inl index)
  · unfold boundedRoot root productionMerkleRoot
    apply merkleRoot_congr (answerBounded fallback input.2)
      (answerBounded fallback transported.2)
      (productionNodePoint linear.channel linear.treeDepth linear.treeNonce)
    · intro level index left right
      exact boundedCombinedCoinOracleEquiv_answer_off coinEquiv outer linear
        hchannels leftOuter leftLinear rightOuter rightLinear hleftOuter
        hleftLinear hrightOuter hrightLinear fallback input
        (productionNodePoint linear.channel linear.treeDepth linear.treeNonce
          level index left right) (by simpa using hnodes)
        (linearNode_ne_combinedLeaf outer linear hchannels leftOuter leftLinear
          input.1 level index left right)
        (linearNode_ne_combinedLeaf outer linear hchannels rightOuter
          rightLinear (coinEquiv input.1) level index left right)
    · intro index
      change answerBounded fallback transported.2
          (leafPoint linear rightLinear (coinEquiv input.1) index) =
        answerBounded fallback input.2
          (leafPoint linear leftLinear input.1 index)
      rw [answerBounded_of_le fallback transported.2 _
          (leafPoint_fits linear rightLinear hrightLinear (coinEquiv input.1)
            index),
        answerBounded_of_le fallback input.2 _
          (leafPoint_fits linear leftLinear hleftLinear input.1 index)]
      exact CoinOracleTransport.coinOracleEquiv_at_right coinEquiv leftPoint
        rightPoint hleft hright hcross input (Sum.inr index)

/-- Exact finite-oracle transport of the serialized production prelude. -/
theorem boundedCombinedCoinOracleEquiv_preEqualityTranscript_exact
    {Coins : Type*} {maxLength : ℕ} (coinEquiv : Coins ≃ Coins)
    (outer linear : TreeGeometry) (hchannels : outer.channel ≠ linear.channel)
    (leftOuter : TreeMaterial outer Coins)
    (leftLinear : TreeMaterial linear Coins)
    (rightOuter : TreeMaterial outer Coins)
    (rightLinear : TreeMaterial linear Coins)
    (hleftOuter : MaterialFits (maxLength := maxLength) outer leftOuter)
    (hleftLinear : MaterialFits (maxLength := maxLength) linear leftLinear)
    (hrightOuter : MaterialFits (maxLength := maxLength) outer rightOuter)
    (hrightLinear : MaterialFits (maxLength := maxLength) linear rightLinear)
    (hnodes : 140 ≤ maxLength) (fallback : OracleBlock)
    (publicDigest r1csDigest : List Byte)
    (proofNonce hadamardTreeNonce : Nonce256)
    (input : Coins × (BoundedBytes maxLength → OracleBlock)) :
    let transported := boundedCombinedCoinOracleEquiv coinEquiv outer linear
      hchannels leftOuter leftLinear rightOuter rightLinear hleftOuter
      hleftLinear hrightOuter hrightLinear input
    preEqualityTranscript publicDigest r1csDigest proofNonce outer.treeNonce
        linear.treeNonce hadamardTreeNonce
        (boundedRoot fallback outer rightOuter (coinEquiv input.1)
          transported.2)
        (boundedRoot fallback linear rightLinear (coinEquiv input.1)
          transported.2) =
      preEqualityTranscript publicDigest r1csDigest proofNonce outer.treeNonce
        linear.treeNonce hadamardTreeNonce
        (boundedRoot fallback outer leftOuter input.1 input.2)
        (boundedRoot fallback linear leftLinear input.1 input.2) := by
  dsimp only
  obtain ⟨houter, hlinear⟩ :=
    boundedCombinedCoinOracleEquiv_roots_exact coinEquiv outer linear
      hchannels leftOuter leftLinear rightOuter rightLinear hleftOuter
      hleftLinear hrightOuter hrightLinear hnodes fallback input
  rw [houter, hlinear]

/-- Load-bearing finite-pROM identity through the complete production
equality-point rejection sampler. -/
theorem boundedCombinedCoinOracleEquiv_equalitySampler_exact
    {Coins : Type*} {maxLength : ℕ} (coinEquiv : Coins ≃ Coins)
    (outer linear : TreeGeometry) (hchannels : outer.channel ≠ linear.channel)
    (leftOuter : TreeMaterial outer Coins)
    (leftLinear : TreeMaterial linear Coins)
    (rightOuter : TreeMaterial outer Coins)
    (rightLinear : TreeMaterial linear Coins)
    (hleftOuter : MaterialFits (maxLength := maxLength) outer leftOuter)
    (hleftLinear : MaterialFits (maxLength := maxLength) linear leftLinear)
    (hrightOuter : MaterialFits (maxLength := maxLength) outer rightOuter)
    (hrightLinear : MaterialFits (maxLength := maxLength) linear rightLinear)
    (hnodes : 140 ≤ maxLength) (fallback : OracleBlock)
    (publicDigest r1csDigest : List Byte)
    (proofNonce hadamardTreeNonce : Nonce256)
    (outerLength trials : ℕ)
    (input : Coins × (BoundedBytes maxLength → OracleBlock))
    (hbudget :
      (preEqualityTranscript publicDigest r1csDigest proofNonce
          outer.treeNonce linear.treeNonce hadamardTreeNonce
          (boundedRoot fallback outer leftOuter input.1 input.2)
          (boundedRoot fallback linear leftLinear input.1 input.2)).length +
        106 + trials * (10 + 16 * outerLength) + 18 ≤ maxLength) :
    let transported := boundedCombinedCoinOracleEquiv coinEquiv outer linear
      hchannels leftOuter leftLinear rightOuter rightLinear hleftOuter
      hleftLinear hrightOuter hrightLinear input
    let simulatedTranscript :=
      preEqualityTranscript publicDigest r1csDigest proofNonce outer.treeNonce
        linear.treeNonce hadamardTreeNonce
        (boundedRoot fallback outer rightOuter (coinEquiv input.1)
          transported.2)
        (boundedRoot fallback linear rightLinear (coinEquiv input.1)
          transported.2)
    let realTranscript :=
      preEqualityTranscript publicDigest r1csDigest proofNonce outer.treeNonce
        linear.treeNonce hadamardTreeNonce
        (boundedRoot fallback outer leftOuter input.1 input.2)
        (boundedRoot fallback linear leftLinear input.1 input.2)
    sampleEqualityPointPrefix (answerBounded fallback transported.2)
        outerLength trials simulatedTranscript =
      sampleEqualityPointPrefix (answerBounded fallback input.2)
        outerLength trials realTranscript := by
  classical
  dsimp only
  let transported := boundedCombinedCoinOracleEquiv coinEquiv outer linear
    hchannels leftOuter leftLinear rightOuter rightLinear hleftOuter hleftLinear
    hrightOuter hrightLinear input
  let realTranscript :=
    preEqualityTranscript publicDigest r1csDigest proofNonce outer.treeNonce
      linear.treeNonce hadamardTreeNonce
      (boundedRoot fallback outer leftOuter input.1 input.2)
      (boundedRoot fallback linear leftLinear input.1 input.2)
  have htranscript :=
    boundedCombinedCoinOracleEquiv_preEqualityTranscript_exact coinEquiv outer
      linear hchannels leftOuter leftLinear rightOuter rightLinear hleftOuter
      hleftLinear hrightOuter hrightLinear hnodes fallback publicDigest
      r1csDigest proofNonce hadamardTreeNonce input
  dsimp only at htranscript
  rw [htranscript]
  have hfiat : isFiatShamirPoint realTranscript :=
    preEqualityTranscript_isFiatShamir publicDigest r1csDigest proofNonce
      outer.treeNonce linear.treeNonce hadamardTreeNonce
      (boundedRoot fallback outer leftOuter input.1 input.2)
      (boundedRoot fallback linear leftLinear input.1 input.2)
  apply sampleEqualityPointPrefix_oracle_congr_fiat_bounded
    (answerBounded fallback input.2) (answerBounded fallback transported.2)
    outerLength trials maxLength realTranscript hfiat hbudget
  intro point hpointFiat hpointLength
  apply boundedCombinedCoinOracleEquiv_answer_off coinEquiv outer linear
    hchannels leftOuter leftLinear rightOuter rightLinear hleftOuter hleftLinear
    hrightOuter hrightLinear fallback input point hpointLength
  · intro index
    cases index with
    | inl outerIndex =>
        exact fiatShamir_ne_merkle hpointFiat .leaf outer.channel
          outer.treeDepth outer.treeNonce outer.leafLength
          (BitVec.ofNat 32 outer.depth) (BitVec.ofNat 64 outerIndex.val)
          (nonceBytes (numericNonceBytes (leftOuter.salts input.1 outerIndex)) ++
            leftOuter.payload input.1 outerIndex)
    | inr linearIndex =>
        exact fiatShamir_ne_merkle hpointFiat .leaf linear.channel
          linear.treeDepth linear.treeNonce linear.leafLength
          (BitVec.ofNat 32 linear.depth) (BitVec.ofNat 64 linearIndex.val)
          (nonceBytes
              (numericNonceBytes (leftLinear.salts input.1 linearIndex)) ++
            leftLinear.payload input.1 linearIndex)
  · intro index
    cases index with
    | inl outerIndex =>
        exact fiatShamir_ne_merkle hpointFiat .leaf outer.channel
          outer.treeDepth outer.treeNonce outer.leafLength
          (BitVec.ofNat 32 outer.depth) (BitVec.ofNat 64 outerIndex.val)
          (nonceBytes
              (numericNonceBytes
                (rightOuter.salts (coinEquiv input.1) outerIndex)) ++
            rightOuter.payload (coinEquiv input.1) outerIndex)
    | inr linearIndex =>
        exact fiatShamir_ne_merkle hpointFiat .leaf linear.channel
          linear.treeDepth linear.treeNonce linear.leafLength
          (BitVec.ofNat 32 linear.depth) (BitVec.ofNat 64 linearIndex.val)
          (nonceBytes
              (numericNonceBytes
                (rightLinear.salts (coinEquiv input.1) linearIndex)) ++
            rightLinear.payload (coinEquiv input.1) linearIndex)

/-- Consequently, the joint finite coin/oracle transport preserves the exact
uniform distribution from which the classical programmable random oracle
game samples. -/
theorem uniform_boundedCombinedCoinOracleEquiv
    {Coins : Type*} {maxLength : ℕ}
    [Fintype Coins] [DecidableEq Coins] [Nonempty Coins]
    (coinEquiv : Coins ≃ Coins)
    (outer linear : TreeGeometry) (hchannels : outer.channel ≠ linear.channel)
    (leftOuter : TreeMaterial outer Coins)
    (leftLinear : TreeMaterial linear Coins)
    (rightOuter : TreeMaterial outer Coins)
    (rightLinear : TreeMaterial linear Coins)
    (hleftOuter : MaterialFits (maxLength := maxLength) outer leftOuter)
    (hleftLinear : MaterialFits (maxLength := maxLength) linear leftLinear)
    (hrightOuter : MaterialFits (maxLength := maxLength) outer rightOuter)
    (hrightLinear : MaterialFits (maxLength := maxLength) linear rightLinear) :
    (PMF.uniformOfFintype
        (Coins × (BoundedBytes maxLength → OracleBlock))).map
        (boundedCombinedCoinOracleEquiv coinEquiv outer linear hchannels
          leftOuter leftLinear rightOuter rightLinear hleftOuter hleftLinear
          hrightOuter hrightLinear) =
      PMF.uniformOfFintype
        (Coins × (BoundedBytes maxLength → OracleBlock)) := by
  exact CoinOracleTransport.uniform_coinOracleEquiv coinEquiv
    (boundedCombinedLeafPoint outer linear leftOuter leftLinear hleftOuter
      hleftLinear)
    (boundedCombinedLeafPoint outer linear rightOuter rightLinear hrightOuter
      hrightLinear)
    (fun coins => boundedCombinedLeafPoint_injective outer linear hchannels
      leftOuter leftLinear hleftOuter hleftLinear coins)
    (fun coins => boundedCombinedLeafPoint_injective outer linear hchannels
      rightOuter rightLinear hrightOuter hrightLinear coins)
    (fun coins => boundedCombinedLeafPoint_cross coinEquiv outer linear
      hchannels leftOuter leftLinear rightOuter rightLinear hleftOuter
      hleftLinear hrightOuter hrightLinear coins)

end VeiledFlock.ProductionBoundedOracle
