import VeiledFlock.ProductionFormalZK

open VeiledFlock.ProductionFormalZK

#print axioms veil_flock_statistical_zk_126
#print axioms veil_flock_statistical_distance_lt_two_pow_neg_126
#print axioms productionSimulator_expected_polytime
#print axioms VeiledFlock.ProductionStatisticalDistance.real_eq_simulated_after_coinEquiv_of_globalGood
#print axioms VeiledFlock.ProductionOperationalGood.globalGood_implies_productionGood
#print axioms VeiledFlock.ProductionOperationalTape.productionDecode_measure_preserving
