import VeiledFlock.Production.Sampling.SamplingScheduleAudit

/-!
# Serialized-domain audit for the production sampling schedule

Every active query generated by the concrete state machine is either a
Fiat--Shamir query whose first encoded byte is `0x01`, or a PoW query whose
first encoded byte is `0x12`.
-/

namespace VeiledFlock.ProductionSamplingScheduleClassification

open VeiledFlock.AdaptiveOracleProgramming
open VeiledFlock.ChallengeSampling
open VeiledFlock.ConcreteOracle
open VeiledFlock.ConcreteParameters
open VeiledFlock.Field128Ghash
open VeiledFlock.Framing
open VeiledFlock.Grinding
open VeiledFlock.OracleCausalOneTimePad
open VeiledFlock.ProductionCausalOperational
open VeiledFlock.ProductionChallengeSampler
open VeiledFlock.ProductionEqualitySampler
open VeiledFlock.ProductionFraming
open VeiledFlock.ProductionGrinding
open VeiledFlock.ProductionGrindingProjection
open VeiledFlock.ProductionNizkCoupling
open VeiledFlock.ProductionNizkExperiment
open VeiledFlock.ProductionPositionProjection
open VeiledFlock.ProductionSamplingLayout
open VeiledFlock.ProductionSamplingOracleSplit
open VeiledFlock.ProductionSamplingSchedule
open VeiledFlock.ProductionSamplingScheduleAudit
open VeiledFlock.ProductionTranscriptFraming
open VeiledFlock.TranscriptSchedule
open VeiledFlock.UniquePositionSampling

theorem isFiatShamirPoint_append {base : List Byte}
    (hbase : isFiatShamirPoint base) (suffix : List Byte) :
    isFiatShamirPoint (base ++ suffix) := by
  cases base with
  | nil => simp [isFiatShamirPoint] at hbase
  | cons head tail => simpa [isFiatShamirPoint] using hbase

theorem afterScalar_isFiatShamir {transcript : List Byte}
    (htranscript : isFiatShamirPoint transcript) (answer : OracleBlock) :
    isFiatShamirPoint (afterScalar transcript answer) := by
  unfold afterScalar
  simpa only [List.append_assoc] using
    isFiatShamirPoint_append htranscript (squeezeScalarTag ++ consumeScalar answer)

theorem afterSlice_isFiatShamir {transcript : List Byte} {length : ℕ}
    (htranscript : isFiatShamirPoint transcript)
    (answer : Fin length → GhashField) :
    isFiatShamirPoint (afterSlice transcript answer) := by
  unfold afterSlice
  simpa only [List.append_assoc] using
    isFiatShamirPoint_append htranscript
      (squeezeSliceTag length ++ sliceAnswerBytes answer)

theorem afterGrind_isFiatShamir' {transcript : List Byte}
    (htranscript : isFiatShamirPoint transcript) (nonce : Word64) :
    isFiatShamirPoint (afterGrind transcript nonce) := by
  unfold afterGrind
  exact isFiatShamirPoint_append htranscript _

theorem appendSchedule_isFiatShamir {Outcome : Type*}
    (start : List Byte)
    (step : ∀ rounds, History (Outcome := Outcome) (rounds + 1) → List Byte)
    (round : ℕ) (answers : History (Outcome := Outcome) round)
    (hstart : isFiatShamirPoint start) :
    isFiatShamirPoint (appendSchedule start step round answers) := by
  obtain ⟨suffix, hsuffix⟩ := appendState_hasPrefix start step round answers
  unfold appendSchedule
  rw [hsuffix]
  exact isFiatShamirPoint_append
    (isFiatShamirPoint_append hstart suffix) counterZero

theorem zerocheckRealByteSchedule_isFiatShamir
    {W : Type*} (shape : BatchShape)
    (causalSecret : ProductionCausalSecret (W := W) shape)
    (completion : Completion OracleBlock (programmedPoints shape))
    (transcript : List Byte) (htranscript : isFiatShamirPoint transcript)
    (witness : W) (coins : ProductionCoins shape) (round : ℕ)
    (answers : History (Outcome := OracleBlock) round) :
    isFiatShamirPoint
      (zerocheckRealByteSchedule shape causalSecret completion transcript witness
        coins round answers) := by
  let masked :=
    VeiledFlock.ProductionCausalScheduleTransport.honestStartTranscript shape
      causalSecret completion (witness, coins.outer.1, coins.outer.2.1)
      coins.outer.2.2
  let step := scalarRoundStep consumeScalar
    (encodeField VeiledFlock.Field128Serialization.encodeGhashField)
    (VeiledFlock.ProductionCausalScheduleTransport.honestFirst shape
      causalSecret completion (witness, coins.outer.1, coins.outer.2.1)
      coins.outer.2.2)
    (VeiledFlock.ProductionCausalScheduleTransport.honestSecond shape
      causalSecret completion (witness, coins.outer.1, coins.outer.2.1)
      coins.outer.2.2)
  change isFiatShamirPoint
    (appendSchedule
      (VeiledFlock.ProductionZerocheckSchedule.start shape transcript masked)
      step round answers)
  apply appendSchedule_isFiatShamir
  unfold VeiledFlock.ProductionZerocheckSchedule.start
  simpa only [List.append_assoc] using isFiatShamirPoint_append htranscript
    (VeiledFlock.ProductionTranscriptFraming.observeScalarSlice
        (VeiledFlock.ProductionZerocheckSchedule.round1Ab shape masked) ++
      VeiledFlock.ProductionTranscriptFraming.observeScalarSlice
        (VeiledFlock.ProductionZerocheckSchedule.round1C shape masked) ++
      squeezeScalarTag)

def ControlFiat {shape : BatchShape} (control : Control shape) : Prop :=
  isFiatShamirPoint control.transcript

theorem acceptScalar_fiat {shape : BatchShape}
    (failed : Finset GhashField) (round start : ℕ) (control : Control shape)
    (answer : OracleBlock) (hfiat : ControlFiat control) :
    ControlFiat (acceptScalar failed round start control answer) := by
  classical
  unfold ControlFiat at hfiat ⊢
  by_cases hzero : round - start = 0
  · by_cases hfailed :
        VeiledFlock.ProductionScalarProjection.scalarFromBlock answer ∈ failed
    · simp [acceptScalar, hzero, hfailed]
      split <;> simp_all [afterScalar_isFiatShamir]
    · simp [acceptScalar, hzero, hfailed, afterScalar_isFiatShamir hfiat]
  · by_cases hdone : control.stageDone
    · simp [acceptScalar, hzero, hdone, hfiat]
    · by_cases hfailed :
          VeiledFlock.ProductionScalarProjection.scalarFromBlock answer ∈ failed
      · simp [acceptScalar, hzero, hdone, hfailed]
        split <;> simp_all [afterScalar_isFiatShamir]
      · simp [acceptScalar, hzero, hdone, hfailed,
          afterScalar_isFiatShamir hfiat]

theorem acceptPositions_fiat {shape : BatchShape}
    (project : GhashField → ℕ) (target start round : ℕ)
    (control : Control shape) (answer : OracleBlock)
    (hfiat : ControlFiat control) :
    ControlFiat (acceptPositions project target start round control answer) := by
  classical
  unfold ControlFiat at hfiat ⊢
  by_cases hzero : round - start = 0
  · simp [acceptPositions, hzero]
    split <;> simp_all [afterScalar_isFiatShamir]
    split <;> simp_all [afterScalar_isFiatShamir]
  · by_cases hdone : control.stageDone
    · simp [acceptPositions, hzero, hdone, hfiat]
    · simp [acceptPositions, hzero, hdone]
      split <;> simp_all [afterScalar_isFiatShamir]
      split <;> simp_all [afterScalar_isFiatShamir]

theorem equalityStep_fiat (shape : BatchShape) (round : ℕ)
    (control : Control shape) (answer : OracleBlock)
    (hfiat : ControlFiat control) :
    ControlFiat (equalityStep shape round control answer) := by
  classical
  unfold ControlFiat at hfiat ⊢
  by_cases hsome : control.equalityPoint.isSome
  · simp [equalityStep, hsome, hfiat]
  · let counter := (round - equalityOffset) % equalityAttemptBlocks
    by_cases hcounter : counter < equalityBlockCount shape
    · let base : Control shape := if counter = 0 then
          { control with equalityBlocks := [] }
        else control
      have hbase : isFiatShamirPoint base.transcript := by
        by_cases hzero : counter = 0 <;> simp [base, hzero, hfiat]
      let blocks := base.equalityBlocks ++ [answer]
      let outer := sliceFromBlocks (m shape - kSkip - 7) blocks
      by_cases hlast : counter + 1 = equalityBlockCount shape
      · by_cases haccept : accepted outer
        · cases hskip : base.skip with
          | none =>
              simp [equalityStep, hsome, counter, hcounter, base, blocks,
                outer, hlast, haccept, hskip, hbase]
          | some skip =>
              simp [equalityStep, hsome, counter, hcounter, base, blocks,
                outer, hlast, haccept, hskip]
              exact afterSlice_isFiatShamir hbase outer
        · simp [equalityStep, hsome, counter, hcounter, base, blocks, outer,
            hlast, haccept]
          split <;> exact afterSlice_isFiatShamir hbase outer
      · simp [equalityStep, hsome, counter, hcounter, base,  hlast,
          hbase]
    · simp [equalityStep, hsome, counter, hcounter, hfiat]

theorem zerocheckStep_fiat
    {W : Type*} (shape : BatchShape)
    (causalSecret : ProductionCausalSecret (W := W) shape)
    (completion : Completion OracleBlock (programmedPoints shape))
    (witness : W) (coins : ProductionCoins shape) (round : ℕ)
    (control : Control shape) (answer : OracleBlock)
    (hfiat : ControlFiat control) :
    ControlFiat
      (zerocheckStep shape causalSecret completion witness coins round control
        answer) := by
  classical
  unfold ControlFiat at hfiat ⊢
  cases heq : control.equalityPoint with
  | none => simp [zerocheckStep, heq, hfiat]
  | some equalityPoint =>
      by_cases hsite : round - zerocheckOffset < programmedPoints shape
      · by_cases hlast :
          round - zerocheckOffset + 1 = programmedPoints shape
        · simp [zerocheckStep, heq, hsite, hlast]
          exact VeiledFlock.ProductionNizkCoupling.afterZerocheck_isFiatShamir
            shape causalSecret completion control.transcript hfiat witness coins
              (historyFromList (control.zerocheckAnswers ++ [answer])
                (programmedPoints shape))
        · simp [zerocheckStep, heq, hsite, hlast, hfiat]
      · simp [zerocheckStep, heq, hsite, hfiat]

theorem blindGrindingStep_fiat {shape : BatchShape} (round : ℕ)
    (control : Control shape) (answer : OracleBlock)
    (hfiat : ControlFiat control) :
    ControlFiat (blindGrindingStep round control answer) := by
  classical
  unfold ControlFiat at hfiat ⊢
  by_cases hdone : control.stageDone
  · simp [blindGrindingStep, hdone, hfiat]
  · by_cases hgood : blindGrindingGood shape answer
    · simp [blindGrindingStep, hdone, hgood]
      exact afterGrind_isFiatShamir' hfiat _
    · simp [blindGrindingStep, hdone, hgood]
      split <;> simp_all

theorem ligeritoStep_fiat {shape : BatchShape} (round : ℕ)
    (control : Control shape) (answer : OracleBlock)
    (hfiat : ControlFiat control) :
    ControlFiat (ligeritoStep round control answer) := by
  classical
  unfold ControlFiat at hfiat ⊢
  by_cases hstate : (round - ligeritoOffset) % ligeritoSiteWidth = 0
  · simp [ligeritoStep, hstate, hfiat]
  · by_cases hdone : control.stageDone
    · simp [ligeritoStep, hstate, hdone, hfiat]
    · by_cases hgood : ligeritoGrindingGood shape
          ((round - ligeritoOffset) / ligeritoSiteWidth) answer
      · simp [ligeritoStep, hstate, hdone, hgood]
        split <;> simp_all [afterGrind_isFiatShamir']
      · simp [ligeritoStep, hstate, hdone, hgood]
        split <;> simp_all

set_option maxRecDepth 30000 in
set_option maxHeartbeats 1000000 in
theorem rawStep_fiat
    {W : Type*} (shape : BatchShape)
    (causalSecret : ProductionCausalSecret (W := W) shape)
    (completion : Completion OracleBlock (programmedPoints shape))
    (witness : W) (coins : ProductionCoins shape) (round : ℕ)
    (control : Control shape) (answer : OracleBlock)
    (hfiat : ControlFiat control) :
    ControlFiat
      (rawStep shape causalSecret completion witness coins round control answer) := by
  classical
  by_cases hstatus : control.status != .live
  · simp [rawStep, hstatus, ControlFiat] at hfiat ⊢
    exact hfiat
  by_cases hskip : round < equalitySkipBlocks
  · by_cases hlast : round + 1 = equalitySkipBlocks
    · simp [rawStep, hstatus, hskip, hlast, ControlFiat]
      exact afterSlice_isFiatShamir hfiat _
    · simp [rawStep, hstatus, hskip, hlast, ControlFiat] at hfiat ⊢
      exact hfiat
  by_cases hequality : round < zerocheckOffset
  · simpa [rawStep, hstatus, hskip, hequality] using
      equalityStep_fiat shape round control answer hfiat
  by_cases hzero : round < blindStateOffset
  · simpa [rawStep, hstatus, hskip, hequality, hzero] using
      zerocheckStep_fiat shape causalSecret completion witness coins round
        control answer hfiat
  by_cases hblindState : round < blindGrindingOffset
  · simp [rawStep, hstatus, hskip, hequality, hzero, hblindState,
      ControlFiat] at hfiat ⊢
    exact hfiat
  by_cases hblindGrind : round < blindChallengeOffset
  · simpa [rawStep, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind] using blindGrindingStep_fiat round control answer hfiat
  by_cases hblind : round < multiplicationAlphaOffset
  · simpa [rawStep, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind, hblind] using acceptScalar_fiat zeroFailure round
        blindChallengeOffset control answer hfiat
  by_cases halpha : round < outerChallengeOffset
  · simpa [rawStep, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind, hblind, halpha] using acceptScalar_fiat zeroOrOneFailure
        round multiplicationAlphaOffset control answer hfiat
  by_cases houterChallenge : round < outerPositionsOffset
  · simpa [rawStep, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind, hblind, halpha, houterChallenge] using
        acceptScalar_fiat zeroFailure round outerChallengeOffset control answer
          hfiat
  by_cases houterPositions : round < linearPositionsOffset
  · simpa [rawStep, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind, hblind, halpha, houterChallenge, houterPositions] using
        acceptPositions_fiat
          (fun value ↦ (rustLowPosition (m shape - 11) value).val)
          (outerL0QueryCount shape) outerPositionsOffset round control answer
          hfiat
  by_cases hlinearPositions : round < linearRhoOffset
  · simpa [rawStep, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind, hblind, halpha, houterChallenge, houterPositions,
      hlinearPositions] using acceptPositions_fiat
        (fun value ↦ (rustLowPosition 13 value).val) veilQueryCount
        linearPositionsOffset round control answer hfiat
  by_cases hlinearRho : round < hadamardPositionsOffset
  · simpa [rawStep, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind, hblind, halpha, houterChallenge, houterPositions,
      hlinearPositions, hlinearRho] using acceptScalar_fiat zeroFailure round
        linearRhoOffset control answer hfiat
  by_cases hhadamardPositions : round < hadamardRhoOffset
  · simpa [rawStep, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind, hblind, halpha, houterChallenge, houterPositions,
      hlinearPositions, hlinearRho, hhadamardPositions] using
        acceptPositions_fiat (fun value ↦ (rustLowPosition 11 value).val)
          veilQueryCount hadamardPositionsOffset round control answer hfiat
  by_cases hhadamardRho : round < productCoefficientOffset
  · simpa [rawStep, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind, hblind, halpha, houterChallenge, houterPositions,
      hlinearPositions, hlinearRho, hhadamardPositions, hhadamardRho] using
        acceptScalar_fiat zeroFailure round hadamardRhoOffset control answer
          hfiat
  by_cases hproduct : round < ligeritoOffset
  · simpa [rawStep, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind, hblind, halpha, houterChallenge, houterPositions,
      hlinearPositions, hlinearRho, hhadamardPositions, hhadamardRho,
      hproduct] using acceptScalar_fiat zeroFailure round
        productCoefficientOffset control answer hfiat
  by_cases hligerito : round < productionSamplingSlots
  · simpa [rawStep, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind, hblind, halpha, houterChallenge, houterPositions,
      hlinearPositions, hlinearRho, hhadamardPositions, hhadamardRho,
      hproduct, hligerito] using ligeritoStep_fiat round control answer hfiat
  simp [rawStep, hstatus, hskip, hequality, hzero, hblindState, hblindGrind,
    hblind, halpha, houterChallenge, houterPositions, hlinearPositions,
    hlinearRho, hhadamardPositions, hhadamardRho, hproduct, hligerito,
    ControlFiat] at hfiat ⊢
  exact hfiat

theorem scheduledStep_fiat
    {W : Type*} (shape : BatchShape)
    (causalSecret : ProductionCausalSecret (W := W) shape)
    (completion : Completion OracleBlock (programmedPoints shape))
    (witness : W) (coins : ProductionCoins shape) (round : ℕ)
    (control : ScheduledControl shape) (answer : OracleBlock)
    (hfiat : ControlFiat control.raw) :
    ControlFiat
      (scheduledStep shape causalSecret completion witness coins round control
        answer).raw := by
  classical
  unfold scheduledStep
  split
  · exact rawStep_fiat shape causalSecret completion witness coins round
      control.raw answer hfiat
  · split
    · simpa [ControlFiat] using hfiat
    · exact rawStep_fiat shape causalSecret completion witness coins round
        control.raw answer hfiat

theorem scheduledControlAfter_fiat
    {W : Type*} (shape : BatchShape)
    (causalSecret : ProductionCausalSecret (W := W) shape)
    (completion : Completion OracleBlock (programmedPoints shape))
    (witness : W) (coins : ProductionCoins shape) (prelude : List Byte)
    (hprelude : isFiatShamirPoint prelude)
    {rounds : ℕ} (answers : History (Outcome := OracleBlock) rounds) :
    ControlFiat
      (scheduledControlAfter shape causalSecret completion witness coins
        prelude answers).raw := by
  induction rounds with
  | zero => simpa [scheduledControlAfter, initialScheduledControl,
      initialControl, ControlFiat] using hprelude
  | succ rounds ih =>
      exact scheduledStep_fiat shape causalSecret completion witness coins
        rounds _ _ (ih _)

theorem fiat_isSamplingBytes {point : List Byte}
    (hpoint : isFiatShamirPoint point) : IsSamplingBytes point :=
  Or.inl hpoint

theorem pow_isSamplingBytes (state : Nonce256) (nonce : Word64) :
    IsSamplingBytes (encodePowPoint state nonce) :=
  Or.inr (VeiledFlock.ProductionFraming.encodePowPoint_head state nonce)

set_option maxRecDepth 30000 in
set_option maxHeartbeats 1000000 in
theorem rawQuery_classified
    {W : Type*} (shape : BatchShape)
    (causalSecret : ProductionCausalSecret (W := W) shape)
    (completion : Completion OracleBlock (programmedPoints shape))
    (witness : W) (coins : ProductionCoins shape) (round : ℕ)
    (control : Control shape) (hfiat : ControlFiat control)
    (point : List Byte)
    (hquery : rawQuery shape causalSecret completion witness coins round
      control = some point) :
    IsSamplingBytes point := by
  classical
  unfold ControlFiat at hfiat
  by_cases hstatus : control.status != .live
  · simp [rawQuery, hstatus] at hquery
  by_cases hskip : round < equalitySkipBlocks
  · simp [rawQuery, hstatus, hskip] at hquery
    subst point
    exact fiat_isSamplingBytes (slicePoint_isFiatShamir hfiat _ _)
  by_cases hequality : round < zerocheckOffset
  · let offset := round - equalityOffset
    let counter := offset % equalityAttemptBlocks
    by_cases hsome : control.equalityPoint.isSome
    · simp [rawQuery, hstatus, hskip, hequality,   hsome] at hquery
    by_cases hcounter : counter < equalityBlockCount shape
    · simp [rawQuery, hstatus, hskip, hequality, offset, counter, hsome,
        hcounter] at hquery
      subst point
      exact fiat_isSamplingBytes (slicePoint_isFiatShamir hfiat _ _)
    · simp [rawQuery, hstatus, hskip, hequality, offset, counter, hsome,
        hcounter] at hquery
  by_cases hzero : round < blindStateOffset
  · let offset := round - zerocheckOffset
    cases heq : control.equalityPoint with
    | none =>
        simp [rawQuery, hstatus, hskip, hequality, hzero,  heq] at hquery
    | some equalityPoint =>
        by_cases hsite : offset < programmedPoints shape
        · simp [rawQuery, hstatus, hskip, hequality, hzero, offset, heq,
            hsite] at hquery
          subst point
          exact fiat_isSamplingBytes
            (zerocheckRealByteSchedule_isFiatShamir shape causalSecret
              completion control.transcript hfiat witness coins offset
                (historyFromList control.zerocheckAnswers offset))
        · simp [rawQuery, hstatus, hskip, hequality, hzero, offset, heq,
            hsite] at hquery
  by_cases hblindState : round < blindGrindingOffset
  · simp [rawQuery, hstatus, hskip, hequality, hzero, hblindState] at hquery
    subst point
    exact fiat_isSamplingBytes (powStatePoint_isFiatShamir hfiat)
  by_cases hblindGrind : round < blindChallengeOffset
  · by_cases hdone : control.stageDone
    · simp [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
        hblindGrind, hdone] at hquery
    · cases hpow : control.powState with
      | none =>
          simp [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
            hblindGrind, hdone, hpow] at hquery
      | some state =>
          simp [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
            hblindGrind, hdone, hpow] at hquery
          subst point
          exact pow_isSamplingBytes state _
  by_cases hblind : round < multiplicationAlphaOffset
  · have hpoint := nonzeroStageQuery_some blindChallengeOffset round control
      point (by simpa [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
        hblindGrind, hblind] using hquery)
    subst point
    exact fiat_isSamplingBytes (scalarPoint_isFiatShamir hfiat)
  by_cases halpha : round < outerChallengeOffset
  · simp [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind, hblind, halpha] at hquery
    have hpoint : point = scalarPoint control.transcript := hquery.2.2.symm
    subst point
    exact fiat_isSamplingBytes (scalarPoint_isFiatShamir hfiat)
  by_cases houterChallenge : round < outerPositionsOffset
  · have hpoint := nonzeroStageQuery_some outerChallengeOffset round control
      point (by simpa [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
        hblindGrind, hblind, halpha, houterChallenge] using hquery)
    subst point
    exact fiat_isSamplingBytes (scalarPoint_isFiatShamir hfiat)
  by_cases houterPositions : round < linearPositionsOffset
  · simp [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind, hblind, halpha, houterChallenge, houterPositions] at hquery
    have hpoint : point = scalarPoint control.transcript := hquery.2.symm
    subst point
    exact fiat_isSamplingBytes (scalarPoint_isFiatShamir hfiat)
  by_cases hlinearPositions : round < linearRhoOffset
  · simp [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind, hblind, halpha, houterChallenge, houterPositions,
      hlinearPositions] at hquery
    have hpoint : point = scalarPoint control.transcript := hquery.2.symm
    subst point
    exact fiat_isSamplingBytes (scalarPoint_isFiatShamir hfiat)
  by_cases hlinearRho : round < hadamardPositionsOffset
  · have hpoint := nonzeroStageQuery_some linearRhoOffset round control point
      (by simpa [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
        hblindGrind, hblind, halpha, houterChallenge, houterPositions,
        hlinearPositions, hlinearRho] using hquery)
    subst point
    exact fiat_isSamplingBytes (scalarPoint_isFiatShamir hfiat)
  by_cases hhadamardPositions : round < hadamardRhoOffset
  · simp [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
      hblindGrind, hblind, halpha, houterChallenge, houterPositions,
      hlinearPositions, hlinearRho, hhadamardPositions] at hquery
    have hpoint : point = scalarPoint control.transcript := hquery.2.symm
    subst point
    exact fiat_isSamplingBytes (scalarPoint_isFiatShamir hfiat)
  by_cases hhadamardRho : round < productCoefficientOffset
  · have hpoint := nonzeroStageQuery_some hadamardRhoOffset round control point
      (by simpa [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
        hblindGrind, hblind, halpha, houterChallenge, houterPositions,
        hlinearPositions, hlinearRho, hhadamardPositions, hhadamardRho] using
          hquery)
    subst point
    exact fiat_isSamplingBytes (scalarPoint_isFiatShamir hfiat)
  by_cases hproduct : round < ligeritoOffset
  · have hpoint := nonzeroStageQuery_some productCoefficientOffset round control
      point (by simpa [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
        hblindGrind, hblind, halpha, houterChallenge, houterPositions,
        hlinearPositions, hlinearRho, hhadamardPositions, hhadamardRho,
        hproduct] using hquery)
    subst point
    exact fiat_isSamplingBytes (scalarPoint_isFiatShamir hfiat)
  by_cases hligerito : round < productionSamplingSlots
  · let offset := round - ligeritoOffset
    let within := offset % ligeritoSiteWidth
    by_cases hstate : within = 0
    · simp [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
        hblindGrind, hblind, halpha, houterChallenge, houterPositions,
        hlinearPositions, hlinearRho, hhadamardPositions, hhadamardRho,
        hproduct, hligerito, offset, within, hstate] at hquery
      subst point
      exact fiat_isSamplingBytes (powStatePoint_isFiatShamir hfiat)
    by_cases hdone : control.stageDone
    · simp [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
        hblindGrind, hblind, halpha, houterChallenge, houterPositions,
        hlinearPositions, hlinearRho, hhadamardPositions, hhadamardRho,
        hproduct, hligerito, offset, within, hstate, hdone] at hquery
    cases hpow : control.powState with
    | none =>
        simp [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
          hblindGrind, hblind, halpha, houterChallenge, houterPositions,
          hlinearPositions, hlinearRho, hhadamardPositions, hhadamardRho,
          hproduct, hligerito, offset, within, hstate, hdone, hpow] at hquery
    | some state =>
        simp [rawQuery, hstatus, hskip, hequality, hzero, hblindState,
          hblindGrind, hblind, halpha, houterChallenge, houterPositions,
          hlinearPositions, hlinearRho, hhadamardPositions, hhadamardRho,
          hproduct, hligerito, offset, within, hstate, hdone, hpow] at hquery
        subst point
        exact pow_isSamplingBytes state _
  simp [rawQuery, hstatus, hskip, hequality, hzero, hblindState, hblindGrind,
    hblind, halpha, houterChallenge, houterPositions, hlinearPositions,
    hlinearRho, hhadamardPositions, hhadamardRho, hproduct, hligerito] at hquery

set_option maxRecDepth 20000 in
theorem freshSchedule_classified
    {W : Type*} (shape : BatchShape)
    (causalSecret : ProductionCausalSecret (W := W) shape)
    (completion : Completion OracleBlock (programmedPoints shape))
    (witness : W) (coins : ProductionCoins shape) (prelude : List Byte)
    (hprelude : isFiatShamirPoint prelude) :
    ScheduleClassified shape causalSecret completion witness coins prelude := by
  classical
  intro round answers point hquery
  simp only [freshSchedule] at hquery
  split at hquery
  · simp at hquery
  · rename_i raw hraw
    split at hquery
    · simp at hquery
    · have hpoint : raw = point := Option.some.inj hquery
      subst point
      exact rawQuery_classified shape causalSecret completion witness coins
        round _ (scheduledControlAfter_fiat shape causalSecret completion witness
          coins prelude hprelude answers) raw hraw

/-- Fully concrete probability bound for the byte-serialized production
sampling schedule.  Its only hypotheses are deterministic public byte
budgets and the audited Fiat--Shamir prefix property. -/
theorem productionSampling_globalBad_probability_le
    {W : Type*} (shape : BatchShape)
    (causalSecret : ProductionCausalSecret (W := W) shape)
    (completion : Completion OracleBlock (programmedPoints shape))
    (witness : W) (coins : ProductionCoins shape) (prelude : List Byte)
    (maxPointLength : ℕ)
    (hbudget : SamplingScheduleBudget prelude maxPointLength)
    (hprelude : isFiatShamirPoint prelude) :
    ((VeiledFlock.OptionalAdaptiveOracle.optionalBadInputs
        (boundedFreshSchedule shape causalSecret completion witness coins
          prelude maxPointLength
          (freshSchedule_fits_of_budget shape causalSecret completion witness
            coins prelude maxPointLength hbudget)
          (freshSchedule_classified shape causalSecret completion witness coins
            prelude hprelude))
        (VeiledFlock.ProductionSamplingBadTape.globalBad shape)).card : ℚ) /
        Fintype.card
          ((SamplingPoint maxPointLength → OracleBlock) ×
            (Fin (productionSamplingSlots + 1) → OracleBlock)) ≤
      VeiledFlock.ProductionSamplingBadTape.samplingAbortBound shape := by
  exact boundedFreshSchedule_globalBad_probability_le shape causalSecret
    completion witness coins prelude maxPointLength
      (freshSchedule_fits_of_budget shape causalSecret completion witness coins
        prelude maxPointLength hbudget)
      (freshSchedule_classified shape causalSecret completion witness coins
        prelude hprelude)

end VeiledFlock.ProductionSamplingScheduleClassification
